### ISSUE TITLE
Change dependency to entity_plus

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/mailchimp#2]
`entity_metadata_wrapper` module is deprecrated.

---

PR: https://github.com/backdrop-contrib/mailchimp/pull/6

**Comment by mazzech** [comment]
+1

**Comment by ghost** [comment]
Here's an initial attempt at this: https://github.com/backdrop-contrib/mailchimp/pull/6
I may need to make further commits as I try to get this module working, will see how it goes...

**Comment by ghost** [comment]
Oops, sorry @herbdool, didn't see your [PR](https://github.com/backdrop-contrib/mailchimp/pull/3) until just now... Don't think it'll work though as I had to make extra edits to remove errors re. a missing `EMWController` class. Do you want to deprecate your PR in favour of mine?
